In [ ]:
#--------------------------------Python Assignment: Data Structures, Functions, Numpy & Pandas------------------------------------------

In [ ]:
# -------------------------------------------Section A: Data Structures & Control Structures-------------------------------------------

In [ ]:
# # --------------------1.Create a list of 5 integers. Perform and print the result of the following operations: 
# append, extend, insert, remove, pop, clear, index, count, sort, and reverse.-------------------------------------------------------

In [1]:
list = [10, 20, 30, 40, 50]
print("Original list:", list)

Original list: [10, 20, 30, 40, 50]


In [2]:
list.append(60)
print("After append:", list)

After append: [10, 20, 30, 40, 50, 60]


In [3]:
list.extend([70, 80])
print("After extend: ",list)

After extend:  [10, 20, 30, 40, 50, 60, 70, 80]


In [4]:
list.insert(2, 25)
print("After extend: ",list)

After extend:  [10, 20, 25, 30, 40, 50, 60, 70, 80]


In [5]:
list.remove(40)
print("After remove 40: ", list)

After remove 40:  [10, 20, 25, 30, 50, 60, 70, 80]


In [6]:
popped = list.pop()
print("After pop:", list)
print("Popped element:", popped)

After pop: [10, 20, 25, 30, 50, 60, 70]
Popped element: 80


In [7]:
list.clear()
print("After clear:", list)

After clear: []


In [8]:
list = [10, 36, 19, 50, 24]
print("Original list:", list)

Original list: [10, 36, 19, 50, 24]


In [9]:
index = list.index(19)
print("Index of 19:", index)

Index of 19: 2


In [10]:
count = list.count(50)
print("Count of 50:", count)

Count of 50: 1


In [11]:
list.sort()
print("After sort:", list)

After sort: [10, 19, 24, 36, 50]


In [12]:
list.reverse()
print("After reverse:", list)

After reverse: [50, 36, 24, 19, 10]


In [ ]:
# --------2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.-----------

In [13]:
students = ("Alice", "Bob", "Charlie")

In [14]:
students

('Alice', 'Bob', 'Charlie')

In [15]:
try:
    students[1] = "David"
except TypeError as e:
    print("Error:", e)

Error: 'tuple' object does not support item assignment


In [16]:
# Reason: Tuples are immutable, means their values cannot be changed after creation.

In [ ]:
# --------------------3. Create a set of integers with some duplicate values. Print the set and explain the output.---------------------

In [17]:
set = {10, 20, 30, 20, 40, 10, 50}
print(set)

{50, 20, 40, 10, 30}


In [18]:
#Reason: Set automatically remove duplicates values and store only unique values.

In [ ]:
# 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [19]:
person = {'Name': 'Sumaiya', 'Age': 20, 'City': 'Hyderabad'}
print(person)

{'Name': 'Sumaiya', 'Age': 20, 'City': 'Hyderabad'}


In [20]:
#Update the age and add a new key 'email'.

person['Age'] = 23
person['e-mail'] = 'example@gmail.com'
print("Updated", person)

Updated {'Name': 'Sumaiya', 'Age': 23, 'City': 'Hyderabad', 'e-mail': 'example@gmail.com'}


In [ ]:
#5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [21]:
age = int(input("Enter your age: "))

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Enter your age:  20


Eligible to vote


In [ ]:
# 6.	Given a 'marks' variable, print the grade:
# - 90 and above: 'A'
# - 75–89: 'B'
# - 50–74: 'C'
# - Below 50: 'Fail'

In [25]:
marks = int(input("Enter your marks: "))

if marks >= 90:
    grade = 'A'
elif marks >= 75 and marks <= 89:
    grade = 'B'
elif marks >= 50 and marks <= 74:
    grade = 'C'
else:
    grade = 'Fail'

print("Your Grade is:", grade)

Enter your marks:  10


Your Grade is: Fail


In [ ]:
# 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [28]:
num = int(input("Enter a number: "))

if num > 0:
    if num % 2 == 0:
        print(f"{num} is positive and even.")
    else:
        print(f"{num} is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print(f"{num} is negative.")

Enter a number:  0


The number is zero.


In [ ]:
#-----------------------------------------------------Section B: Numpy-----------------------------------------------------------------

In [ ]:
# 8.	Create:
# - A scalar using np.array(5)
# - A 1D array with values 1 to 5
# - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [29]:
import numpy as np
scalar = np.array(5)
print("Scalar array:")
print(scalar)

Scalar array:
5


In [30]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


In [31]:
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("2D Array:")
print(array_2d)

2D Array:
[[10 20 30]
 [40 50 60]]


In [ ]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [32]:
import numpy as np
random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Integer Array (0–100):")
print(random_array)

4x4 Random Integer Array (0–100):
[[51 19 13 77]
 [ 0 88 65 70]
 [17 46 36 96]
 [26 44 83 23]]


In [ ]:
#10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [33]:
import numpy as np
import pandas as pd

array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

print("2D NumPy Array:")
print(array_2d)

2D NumPy Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [34]:
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

print("Pandas DataFrame:")
print(df)

Pandas DataFrame:
    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


In [ ]:
#--------------------------------------------------Section C: Exploring Pandas---------------------------------------------------------

In [ ]:
# 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# - Use .info(), .describe()
# - Select 'Name' and 'City' columns
# - Drop 'City' column
# - Fill any missing values in 'Salary' column with the mean
# - Remove any duplicate rows

In [24]:
data = {
    'Name': ['Aisha', 'Rahul', 'Neha', 'Arjun', 'Fatima', 
             'Ravi', 'Raju', 'Karan', 'Meena', 'Ravi'],
    'Age': [25, 30, 22, 28, 35, 26, 22, 31, 29, 26],
    'City': ['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Hyderabad',
             'Delhi', 'Chennai', 'Pune', 'Kolkata', 'Delhi'],
    'Salary': [45000, 52000, np.nan, 48000, 55000, 50000, 52000, np.nan, 47000, 50000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df, "\n")

Original DataFrame:
      Name  Age       City   Salary
0   Aisha   25      Delhi  45000.0
1   Rahul   30     Mumbai  52000.0
2    Neha   22    Chennai      NaN
3   Arjun   28    Kolkata  48000.0
4  Fatima   35  Hyderabad  55000.0
5    Ravi   26      Delhi  50000.0
6    Raju   22    Chennai  52000.0
7   Karan   31       Pune      NaN
8   Meena   29    Kolkata  47000.0
9    Ravi   26      Delhi  50000.0 



In [25]:
# Display info and statistics
print("DataFrame Info:")
print(df.info(), "\n")

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None 



In [26]:
print("Descriptive Statistics:")
print(df.describe(), "\n")

Descriptive Statistics:
             Age        Salary
count  10.000000      8.000000
mean   27.400000  49875.000000
std     4.060651   3181.980515
min    22.000000  45000.000000
25%    25.250000  47750.000000
50%    27.000000  50000.000000
75%    29.750000  52000.000000
max    35.000000  55000.000000 



In [27]:
#Select 'Name' and 'City' columns
print("Selected Columns (Name and City):")
print(df[['Name', 'City']], "\n")

Selected Columns (Name and City):
     Name       City
0   Aisha      Delhi
1   Rahul     Mumbai
2    Neha    Chennai
3   Arjun    Kolkata
4  Fatima  Hyderabad
5    Ravi      Delhi
6    Raju    Chennai
7   Karan       Pune
8   Meena    Kolkata
9    Ravi      Delhi 



In [28]:
# Drop the 'City' column
df_dropped = df.drop('City', axis=1)
print("DataFrame after dropping 'City' column:\n", df_dropped, "\n")

DataFrame after dropping 'City' column:
      Name  Age   Salary
0   Aisha   25  45000.0
1   Rahul   30  52000.0
2    Neha   22      NaN
3   Arjun   28  48000.0
4  Fatima   35  55000.0
5    Ravi   26  50000.0
6    Raju   22  52000.0
7   Karan   31      NaN
8   Meena   29  47000.0
9    Ravi   26  50000.0 



In [29]:
# Fill missing values in 'Salary' column with the mean
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)
print(f"Mean Salary = {mean_salary:.2f}")
print("DataFrame after filling missing salaries:\n", df, "\n")

Mean Salary = 49875.00
DataFrame after filling missing salaries:
      Name  Age       City   Salary
0   Aisha   25      Delhi  45000.0
1   Rahul   30     Mumbai  52000.0
2    Neha   22    Chennai  49875.0
3   Arjun   28    Kolkata  48000.0
4  Fatima   35  Hyderabad  55000.0
5    Ravi   26      Delhi  50000.0
6    Raju   22    Chennai  52000.0
7   Karan   31       Pune  49875.0
8   Meena   29    Kolkata  47000.0
9    Ravi   26      Delhi  50000.0 



In [30]:
# Remove duplicate rows
df_unique = df.drop_duplicates()
print("DataFrame after removing duplicates:\n", df_unique)

DataFrame after removing duplicates:
      Name  Age       City   Salary
0   Aisha   25      Delhi  45000.0
1   Rahul   30     Mumbai  52000.0
2    Neha   22    Chennai  49875.0
3   Arjun   28    Kolkata  48000.0
4  Fatima   35  Hyderabad  55000.0
5    Ravi   26      Delhi  50000.0
6    Raju   22    Chennai  52000.0
7   Karan   31       Pune  49875.0
8   Meena   29    Kolkata  47000.0
